### ISSUE TITLE
Retrain only the occupancy network?

### ISSUE THREAD

**Issue by Okaerikoto** [neuralbodies/leap#1]
According to the config file `configurations/leap_model.yml`, training the occupancy model requires the pretrained LBS networks `./trained_models/inv_lbs/movi_split/model_best.pt` and `./trained_models/fwd_lbs/movi_split/model_best.pt` which are not released . Can you release those?

**Comment by Okaerikoto** [comment]
As a workaround, I modified the following two functions to load the fwd_lbs and inv_lbs parameters from the provided `sample_body.pt`, leaving the leap occupancy network uninitialized.

        # in leap/training_code_train_leap.py
            leap_path = '/ps/project/rib_cage_breathing/Code/Downloaded/leap/leap_pretrained_model/sample_body.pt'
            from leap.modules import LEAPModel
            # load only the pretrained fwd_lbs and inv_lbs networks and not the occupancy network 
            model = LEAPModel.load_from_file(leap_path, lbs_only=True)
            model = model.to(device='cuda')
        
        # in leap/modules/modules.py
            @classmethod
            def load_from_file(cls, file_path, lbs_only=False):
                state_dict = cls.parse_pytorch_file(file_path)
                config = state_dict['leap_model_config']
                model_state_dict = state_dict['leap_model_model']
        
                leap_model = cls(
                    inv_lbs=INVLBS.from_cfg(config['inv_lbs_model_config']),
                    fwd_lbs=FWDLBS.from_cfg(config['fwd_lbs_model_config']),
                    leap_occupancy_decoder=LEAPOccupancyDecoder.from_cfg(config))
        
                if lbs_only:
                    # remove all the parameters from LEAP occ model from the dictionary so that they are not loaded
                    keys = model_state_dict.keys()
                    model_state_dict = model_state_dict.copy()
                    [model_state_dict.pop(k) for k in keys if 'leap_occupancy_decoder' not in k]
        
                # set the strict parameters so that loading with missing parameters is tolerated.
                leap_model.load_state_dict(model_state_dict, strict=not lbs_only)
                return leap_model

**Comment by markomih** [comment]
Hi Okaerikoto, thank you for sharing the workaround.
